- name: install and run nginx
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start the service
    ansible.builtin.service:
      name: start nginx
      state: started
      enabled: yes