- name: play level variable
  hosts: local
  connection: local
  vars:
   COURSE: "Devops with vignesh"
   DURATION: "140hrs"
   TRAINER: "vignesh"
  tasks:
    - name: print variables
      ansible.builtin.debug:
        msg: "course is {{ COURSE }} {{ DURATION }} {{ TRAINER }}"