- name: print username and password
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: please enter usrname
    private: false

  - name: password
    prompt: please enter password
    private: true

  tasks:
  - name: print info
    ansible.builtin.debug:
     msg: "username is {{ username }}, password is {{ password }}"