- name: variable preferences
  hosts: local 
  connection: local
  vars:
    NAME: "ansible from play"
  #vars_files:
    #- course.yaml
  # vars_prompt:
  # - name: NAME
  #   prompt: please enter name
  #   private: false
  tasks:
  - name: print name
    #vars:
      #NAME: "ansible from task"
    ansible.builtin.debug:
      msg: "Hi, {{ NAME }}"