- name: ansible command vs shell module test 
  hosts: local
  connection: local
  tasks:
  - name: command module test
    #ansible.builtin.command: cat /etc/password | grep root
    ansible.builtin.shell: cat /etc/passwd | grep root
    register: user_output

  - name: print the user_output
    ansible.builtin.debug:
      msg: "{{ user_output }}"
