- name: demo on filters
  hosts: local 
  connection: local
  vars: 
    myip: 244.256.245.55
    topics: linux, shell, ansible, terraform
    tagsmap:
      name: ansible
      project: roboshop
      component: catalogue

    tagslist: [
        {
            "key": "name",
            "value": "ansible"
        },
        {
            "key": "project",
            "value": "roboshop"
        },
        {
            "key": "component",
            "value": "catalogue"
        }
    ]
    course: "I Am Learning Linux"

  tasks:
  - name: greeting
    ansible.builtin.debug:
      msg: "Hi vignesh, {{ GREETING | default('goodmorning') }}"

  - name: convert string to list
    ansible.builtin.debug:
      msg: " {{ topics | split(',') }}"

  - name: convert map to list 
    ansible.builtin.debug:
      msg: "{{ tagsmap | dict2items }}" 

  - name: convert list to map 
    ansible.builtin.debug:
      msg: "{{ tagslist | items2dict }}"

  - name: read student yaml
    ansible.builtin.set_fact:
      student_yaml: "{{ lookup('file', 'students.yaml') | from_yaml }}"

  - name: convert yaml to json
    ansible.builtin.debug:
      msg: "{{ student_yaml | to_nice_json }}"

  - name: convert to lower case
    ansible.builtin.debug:
      msg: "{{ course | lower }}"

  - name: check ipv4
    ansible.builtin.debug:
      msg: "{{ myip | ansible.utils.ipv4 }}"

